module.exports = {
	MOVIES: "show movies",
	ADD_MOVIE: "add",
	VOTE_MOVIE: "vote",
	"FRIDAY_MOVIE": ['friday movie', 'Friday Movie', 'friday', 'Friday', 'Friday Movies', 'friday movies'],
	DANNY: ['Danny', 'Danny Nguyen', 'sexy'],
	SCOTT: ['Scott', 'Scott Jones', 'LegionEpicWin', 'hottie'],
	MATT: ['Matt', 'matt'],
	JOECARPENITO: ['Joe C', 'carpenito', 'Carpenito'],
	JOEMORGAN: ['Joe Morgan', 'Morgan'],
	LANCE: ['Lance', 'lance'],
	FORREST: ['forrest', 'Forrest'],
	MILOS: ['milos', 'Milos'],
	TOM: ['Tom', 'tom'],
	CHRIS: ['Chris', 'chris'],
	AMY: ['Amy', 'amy'],
	ROSHAN: ['Roshan', 'roshan'],
	PETE: ['pete', 'Pete'],
	EVAN: ['Evan', 'evan'],
	AMBER: ['Amber', 'amber']
}